method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 2
  env:
    values:
      - "AhnChemo-v0"
  episodes_avail:
    values:
      - 15000
  batch_size:
   values:
     - 256
  device:
    values:
      - "cuda:5"
  n_episodes:
    values:
      - 5000
  alpha:
    values:
      - 1.0
  frame_stack:
    values:
      - 20
  include_previous_action:
    values:
      - True
  qf_lr:
    values:
      - 0.0001
  behavior_policy:
    values:
      - "biased_ahnChemo"
  num_checkpoints:
    values:
      - 50
program: algorithms/cql_standard_dtrgym.py

command:
  - python
  - ${program}
  - train
  - all_data_sweeps/cancer/cql_standard_config_dtrgym.yaml
